name: Martin Gingras
safe: true
permalink: /:categories/:title
url: http://mgingras.ca
markdown: kramdown
port: 4000
paginate: 5
auto: true
future: false
exclude:
- README.md
- CNAME
- params.json
- Gemfile
- Gemfile.lock
